# @format

services:
  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    environment:
      - FAMLY_PICTURES_FOLDER=/app/pictures
    volumes:
      - ./pictures:/app/pictures
    stdin_open: true
    tty: true
    entrypoint: ["famly-fetch", "-e"]
