query LearningJourneyQuery($childId: ChildId!, $observationIds: [ObservationId!], $variants: [ObservationVariant!], $next: ObservationCursor, $first: Int!) {
  childDevelopment {
    observations(
      first: $first
      childIds: [$childId]
      observationIds: $observationIds
      statuses: [SENT]
      variants: $variants
      after: $next
    ) {
      results {
        ...ObservationDataWithNoComments
      }
      next
    }
  }
}

fragment ObservationDataWithNoComments on Observation {
  id
  version
  children {
    id
    name
  }
  createdBy {
    name {
      fullName
    }
  }
  status {
    createdAt
  }
  variant
  settings {
    assessmentSetting {
      assessmentSettingsId
      title
    }
  }
  remark {
    body
    richTextBody
    date
    areas {
      area {
        frameworkId
        id
        parentId
        title
        description
        abbr
        color
        placement
        deletedAt
        framework {
          id
          title
          owner
        }
      }
      refinement
      note
      areaRefinementSettings {
        ageBandSetting {
          ...AgeBandSetting
        }
        assessmentOptionSetting {
          ...AssessmentOptionSetting
        }
      }
    }
    customFieldValues {
      customFieldSetting {
        assessmentSettingsId
        customFieldId
        label
        order
      }
      value
    }
  }
  nextStep {
    body
    richTextBody
  }
  images {
    height
    width
    id
    secret {
      crop
      expires
      key
      path
      prefix
    }
  }
  videos {
    ... on TranscodingVideo {
      videoId: id
    }
    ... on TranscodedVideo {
      duration
      height
      videoId: id
      thumbnailUrl
      videoUrl
      width
    }
  }
  files {
    fileId: id
    url
    filename: name
  }
}

fragment AgeBandSetting on AgeBandSetting {
  ageBandSettingId
  assessmentSettingsId
  from
  to
  label
}

fragment AssessmentOptionSetting on AssessmentOptionSetting {
  assessmentOptionSettingId
  assessmentSettingsId
  backgroundColor
  fontColor
  label
}
